//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmoviliariaWeb.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBInmobiliariaEntities : DbContext
    {
        public DBInmobiliariaEntities()
            : base("name=DBInmobiliariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Comision> Comisions { get; set; }
        public virtual DbSet<ContratoPropiedad> ContratoPropiedads { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Estacionamiento> Estacionamientoes { get; set; }
        public virtual DbSet<EstadoPropiedad> EstadoPropiedads { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<Propiedade> Propiedades { get; set; }
        public virtual DbSet<Sede> Sedes { get; set; }
        public virtual DbSet<Telefono> Telefonoes { get; set; }
        public virtual DbSet<Tipo_Tel> Tipo_Tel { get; set; }
        public virtual DbSet<TiposContrato> TiposContratoes { get; set; }
        public virtual DbSet<TiposPropiedad> TiposPropiedads { get; set; }
    }
}
