//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmoviliariaWeb.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int id_tel { get; set; }
        public string numero { get; set; }
        public int cliente { get; set; }
        public int tipo_telefono { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Tipo_Tel Tipo_Tel { get; set; }
    }
}
